#!/bin/sh

# Mount CDROM
mkdir /cdrom
mount -t iso9660 /dev/cdrom /cdrom

# Update modules
depmod -a

# Load ZFS
modprobe zfs

# Load installation packages
udpkg -i /cdrom/pool/main/t/truenas-install/*.deb

# Drop to debug shell
/bin/sh
