#!/bin/bash
set -e

case "$1" in
    configure)
        mkdir -p /etc/nginx/conf.d
        mkdir -p /var/www/html
        install -m 644 /usr/share/truenas-installer/nginx.conf /etc/nginx/nginx.conf
        install -m 644 /usr/share/truenas-installer/cert.conf /etc/nginx/conf.d/cert.conf
        install -m 644 /usr/share/truenas-installer/index.html /var/www/html/index.html
        rm -f /etc/nginx/sites-enabled/default /etc/nginx/sites-available/default
        systemctl reload nginx || true
        ;;
esac
